image:
  - Visual Studio 2019
  
environment:
  matrix:
  - TOXENV: py39

install:
  #- ps: Install-Package Python -ForceBootstrap
  - ps: py -m venv env
  - ps: .\env\Scripts\activate
  #- ps: py -m pip install flask numpy pillow matplotlib Flask-WTF wtforms --upgrade pip

test_script:
  - ps: .\env\Scripts\activate
  - ps: py main.py
  - ps: py tests\pytest.py
  

build: off
