install:
- py -m venv env
- env/Scripts/activate
- pip install flask
- pip install numpy
- pip install pillow
- pip install matplotlib
- pip install -U Flask-WTF
- pip install wtforms
test_script:
- py ./main.py
