image:
  - Visual Studio 2019

environment:
  matrix:
    - PYTHON: "C:\\Python39"

install:
  - ps: Install-Package Python -ForceBootstrap
  - ps: '%PYTHON%\python.exe -m venv env'
  - ps: .\env\Scripts\activate
  - ps: '%PYTHON%\python.exe -m pip install flask numpy pillow matplotlib Flask-WTF wtforms'

test_script:
  - ps: .\env\Scripts\activate
  - ps: '%PYTHON%\python.exe main.py'

build: off
